# Generated by Django 3.2.6 on 2021-08-26 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_whatwedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 0, 40, 47, 804753)),
        ),
    ]
