# Generated by Django 3.2.6 on 2021-08-26 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210827_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 1, 59, 53, 787206)),
        ),
    ]
